config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get 'posts/new'
  get '/top' => 'homes#top'
  get '/new' => 'posts#new'

  get '/posts' => 'posts#index'
  post '/posts' => 'posts#create'

  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  get '/posts/:id' => 'posts#show', as: 'post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	attachment :image
	validates :title, presence: true,length:{maximum: 20}
	validates :weather, presence: true,length:{maximum: 10}
	validates :body, presence: true,length:{maximum: 200}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	@article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "新規投稿に成功しました"
      redirect_to post_path(@article.id)
    else
      render "new"
    end
=begin
    @article.save
    redirect_to post_path(article.id)
=end
  end

  def index
    @articles = Article.all
    @article = Article.new
  end

  def show
  	@article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "編集に成功しました"
      redirect_to post_path(@article.id)
    else
      render "new"
    end
=begin
    article = Article.find(params[:id])
    article.update(article_params)
    redirect_to post_path(article.id)
=end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to :action => "index"
  end

  def article_params
    params.require(:article).permit(:title, :weather, :body, :image)
  end
  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/homes/top.html.erb
<h1>プロフィール</h1>

<div class="marquee">
  <div class="marquee-inner">こんにちは！動いてます！</div>
</div>

<h1>伊神誠人</h1>

<h2><%= link_to "新規投稿", new_path %><h2>

<a href="https://mako-channel.com/programming/ruby-collabo"target="_blank">ブログでアウトプットしました<br></a>

<a href="https://mako-channel.com/programming/ruby-collabo"target="_blank">
<img src="wing.gif" border="0">
<a>

<div class="picture">
	<%= image_tag 'chopper.jpg',:size =>'600x480' ,class:"circle"%>
</div>

app/views/layouts/_error_messages.html.erb
<% if @article.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IkamiDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> トップ</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/new">新規投稿</a></li>
        <li><a href="/posts">投稿一覧</a></li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for @article, :url => {:action => 'update'} do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>天気</h4>
    <%= f.text_area :weather%>

    <h4>本文</h4>
    <%= f.text_area :body %>

    <h4>画像</h4>
  	<%= f.attachment_field :image %>

	<%= f.submit '保存' %>
<% end %>

app/views/posts/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<%= form_for @article, :url => {:action => 'create'} do |f| %>
				<h4>タイトル</h4>
		    		<%= f.text_field :title %>
				<h4>天気</h4>
		    		<%= f.text_area :weather%>
				<h4>本文</h4>
		    		<%= f.text_field :body %>
		    	<h4>画像</h4>
  					<%= f.attachment_field :image %>
				<%= f.submit '投稿' %>
		</div>
	<div class="col-md-8">


	<h1>投稿一覧</h1>
	<table class="table">
		<tr>
			<th>タイトル</th>
			<th>天気</th>
			<th>本文</th>
			<th>画像</th>
		</tr>
		<% @articles.each do |article| %>
		<tr>
			<th><%=link_to article.title, "/posts/#{article.id}" %></th>
			<td><%=link_to article.weather, "/posts/#{article.id}" %></td>
			<td><%=link_to article.body , "/posts/#{article.id}" %></td>
			<td><%= attachment_image_tag(article, :image, :fill, 30, 30, fallback: "sample.png", size: "30x30") %></td>
		</tr>
		<% end %>
	</table>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿ページ</h1>

<% if @article.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @article, :url => {:action => 'create'} do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>天気</h4>
    <%= f.text_area :weather%>

    <h4>本文</h4>
    <%= f.text_field :body %>

    <h4>画像</h4>
    <%= f.attachment_field :image %>

    <%= f.submit '投稿' %>

<% end %>

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table">
  <tr>
    <th>タイトル</th>
    <th>天気</th>
    <th>本文</th>
    <th>画像</th>
  </tr>
  <tr>
    <td><%= @article.title %></td>
    <td><%= @article.weather %></td>
    <td><%= @article.body %></td>
    <td><%= attachment_image_tag(@article, :image, :fill, 30, 30, fallback: "sample.png", size: "30x30") %></td>
  </tr>
</table>

<%= link_to "編集", edit_post_path(@article.id) %>
<%= link_to "削除", destroy_post_path(@article.id), method: :delete, "data-confirm" => "削除しますか？" %>

app/views/root/top.html.erb
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@post) do |f| %>

    <h4>タイトル</h4>
    <%= f.text_field :title %>

    <h4>本文</h4>
    <%= f.text_area :body %>

	<h4>本文</h4>
    <%= f.text_field :title %>

    <%= f.submit '投稿' %>

<% end %>